<?php

$finder = Symfony\Component\Finder\Finder::create()
    ->in([
        __DIR__ . '/config',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->name('*.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return (new PhpCsFixer\Config)
    ->setRules([
        // rule sets
        '@PSR1'                                            => true,
        '@PSR12'                                           => true,
        '@PSR12:risky'                                     => true,
        '@PSR2'                                            => true,
        // alias
        'array_push'                                       => true,
        'backtick_to_shell_exec'                           => false,
        'ereg_to_preg'                                     => true,
        'mb_str_functions'                                 => true,
        'no_alias_functions'                               => true,
        'no_alias_language_construct_call'                 => true,
        'no_mixed_echo_print'                              => true,
        'pow_to_exponentiation'                            => true,
        'random_api_migration'                             => true,
        'set_type_to_cast'                                 => true,
        // array
        'array_syntax'                                     => ['syntax' => 'short'],
        'no_multiline_whitespace_around_double_arrow'      => true,
        'no_whitespace_before_comma_in_array'              => true,
        'normalize_index_brace'                            => true,
        'trailing_comma_in_multiline'                      => true,
        'trim_array_spaces'                                => true,
        'whitespace_after_comma_in_array'                  => true,
        // basic
        'braces'                                           => true,
        'encoding'                                         => true,
        'non_printable_character'                          => true,
        'psr_autoloading'                                  => true,
        // casing
        'constant_case'                                    => true,
        'lowercase_keywords'                               => true,
        'lowercase_static_reference'                       => true,
        'magic_constant_casing'                            => true,
        'magic_method_casing'                              => true,
        'native_function_casing'                           => true,
        'native_function_type_declaration_casing'          => true,
        // cast notation
        'cast_spaces'                                      => ['space' => 'single'],
        'lowercase_cast'                                   => true,
        'modernize_types_casting'                          => true,
        'no_short_bool_cast'                               => true,
        'no_unset_cast'                                    => true,
        'short_scalar_cast'                                => true,
        // class notation
        'class_attributes_separation'                      => ['elements' => ['const' => 'one', 'method' => 'one', 'property' => 'one']],
        'class_definition'                                 => true,
        'final_class'                                      => false,
        'final_internal_class'                             => true,
        'final_public_method_for_abstract_class'           => false,
        'no_blank_lines_after_class_opening'               => true,
        'no_null_property_initialization'                  => false,
        'no_php4_constructor'                              => true,
        'no_unneeded_final_method'                         => true,
        'ordered_class_elements'                           => false,
        'ordered_interfaces'                               => false,
        'ordered_traits'                                   => false,
        'protected_to_private'                             => false,
        'self_accessor'                                    => true,
        'self_static_accessor'                             => false,
        'single_class_element_per_statement'               => true,
        'single_trait_insert_per_statement'                => false,
        'visibility_required'                              => true,
        // class usage
        'date_time_immutable'                              => false,
        'comment_to_phpdoc'                                => true,
        'multiline_comment_opening_closing'                => true,
        'no_empty_comment'                                 => false,
        'no_trailing_whitespace_in_comment'                => true,
        'single_line_comment_style'                        => false,
        // constant notation
        'native_constant_invocation'                       => false,
        // control structure
        'elseif'                                           => true,
        'include'                                          => true,
        'no_alternative_syntax'                            => true,
        'no_break_comment'                                 => true,
        'no_superfluous_elseif'                            => true,
        'no_trailing_comma_in_singleline'                  => true,
        'no_unneeded_control_parentheses'                  => true,
        'no_unneeded_curly_braces'                         => true,
        'no_useless_else'                                  => true,
        'simplified_if_return'                             => true,
        'switch_case_semicolon_to_colon'                   => true,
        'switch_case_space'                                => true,
        'switch_continue_to_break'                         => true,
        'yoda_style'                                       => false,
        // doctrine annotation
        // # these rules are only for laravel projects
        // function notation
        'combine_nested_dirname'                           => true,
        'fopen_flag_order'                                 => true,
        'fopen_flags'                                      => true,
        'function_declaration'                             => true,
        'function_typehint_space'                          => true,
        'implode_call'                                     => true,
        'lambda_not_used_import'                           => true,
        'method_argument_space'                            => false,
        'native_function_invocation'                       => false,
        'no_spaces_after_function_name'                    => true,
        'no_unreachable_default_argument_value'            => false,
        'no_useless_sprintf'                               => true,
        'nullable_type_declaration_for_default_null_value' => false,
        'phpdoc_to_param_type'                             => false,
        'phpdoc_to_return_type'                            => false,
        'regular_callable_call'                            => true,
        'return_type_declaration'                          => true,
        'single_line_throw'                                => false,
        'static_lambda'                                    => false,
        'use_arrow_functions'                              => false,
        'void_return'                                      => false,
        // import
        'fully_qualified_strict_types'                     => true,
        'global_namespace_import'                          => false,
        'group_import'                                     => false,
        'no_leading_import_slash'                          => true,
        'no_unused_imports'                                => true,
        'ordered_imports'                                  => ['sort_algorithm' => 'length'],
        'single_import_per_statement'                      => true,
        'single_line_after_imports'                        => true,
        // language construct
        'combine_consecutive_issets'                       => true,
        'combine_consecutive_unsets'                       => true,
        'declare_equal_normalize'                          => ['space' => 'single'],
        'dir_constant'                                     => true,
        'error_suppression'                                => ['mute_deprecation_error' => true, 'noise_remaining_usages' => false, 'noise_remaining_usages_exclude' => []],
        'explicit_indirect_variable'                       => true,
        'function_to_constant'                             => ['functions' => ['get_class', 'get_called_class', 'php_sapi_name', 'phpversion', 'pi']],
        'is_null'                                          => false,
        'no_unset_on_property'                             => true,
        'single_space_after_construct'                     => true,
        // list notation
        'list_syntax'                                      => ['syntax' => 'short'],
        // namespace notation
        'blank_line_after_namespace'                       => true,
        'clean_namespace'                                  => true,
        'no_blank_lines_before_namespace'                  => false,
        'no_leading_namespace_whitespace'                  => true,
        'single_blank_line_before_namespace'               => true,
        // naming
        'no_homoglyph_names'                               => true,
        // operator
        'binary_operator_spaces'                           => ['default' => 'align'],
        'concat_space'                                     => ['spacing' => 'one'],
        'increment_style'                                  => ['style' => 'post'],
        'logical_operators'                                => true,
        'new_with_braces'                                  => false,
        'not_operator_with_space'                          => false,
        'not_operator_with_successor_space'                => true,
        'object_operator_without_whitespace'               => true,
        'operator_linebreak'                               => false,
        'standardize_increment'                            => true,
        'standardize_not_equals'                           => true,
        'ternary_operator_spaces'                          => true,
        'ternary_to_elvis_operator'                        => true,
        'ternary_to_null_coalescing'                       => true,
        'unary_operator_spaces'                            => true,
        // php tag
        'blank_line_after_opening_tag'                     => true,
        'echo_tag_syntax'                                  => true,
        'full_opening_tag'                                 => true,
        'linebreak_after_opening_tag'                      => true,
        'no_closing_tag'                                   => true,
        // phpunit
        // # we don't use these rules on phpunit in order to avoid 'fear' of writing tests
        // phpdoc
        'align_multiline_comment'                          => ['comment_type' => 'phpdocs_only'],
        'general_phpdoc_annotation_remove'                 => false,
        'general_phpdoc_tag_rename'                        => true,
        'no_blank_lines_after_phpdoc'                      => true,
        'no_empty_phpdoc'                                  => true,
        'no_superfluous_phpdoc_tags'                       => false,
        'phpdoc_add_missing_param_annotation'              => true,
        'phpdoc_align'                                     => ['align' => 'vertical'],
        'phpdoc_annotation_without_dot'                    => false,
        'phpdoc_indent'                                    => true,
        'phpdoc_inline_tag_normalizer'                     => true,
        'phpdoc_line_span'                                 => true,
        'phpdoc_no_access'                                 => true,
        'phpdoc_no_alias_tag'                              => ['replacements' => ['type' => 'var', 'link' => 'see']],
        'phpdoc_no_empty_return'                           => false,
        'phpdoc_no_package'                                => true,
        'phpdoc_no_useless_inheritdoc'                     => true,
        'phpdoc_order_by_value'                            => false,
        'phpdoc_order'                                     => true,
        'phpdoc_return_self_reference'                     => true,
        'phpdoc_scalar'                                    => true,
        'phpdoc_separation'                                => false,
        'phpdoc_single_line_var_spacing'                   => true,
        'phpdoc_summary'                                   => false,
        'phpdoc_tag_casing'                                => true,
        'phpdoc_tag_type'                                  => true,
        'phpdoc_to_comment'                                => false,
        'phpdoc_trim_consecutive_blank_line_separation'    => true,
        'phpdoc_trim'                                      => true,
        'phpdoc_types'                                     => true,
        'phpdoc_types_order'                               => true,
        'phpdoc_var_annotation_correct_order'              => true,
        'phpdoc_var_without_name'                          => false,
        // return notation
        'no_useless_return'                                => false,
        'return_assignment'                                => false,
        'simplified_null_return'                           => false,
        // semicolon
        'multiline_whitespace_before_semicolons'           => true,
        'no_empty_statement'                               => true,
        'no_singleline_whitespace_before_semicolons'       => true,
        'semicolon_after_instruction'                      => true,
        'space_after_semicolon'                            => true,
        // strict
        'declare_strict_types'                             => false,
        'strict_comparison'                                => true,
        'strict_param'                                     => true,
        // string notation
        'escape_implicit_backslashes'                      => true,
        'explicit_string_variable'                         => true,
        'heredoc_to_nowdoc'                                => true,
        'no_binary_string'                                 => true,
        'no_trailing_whitespace_in_string'                 => true,
        'simple_to_complex_string_variable'                => true,
        'single_quote'                                     => true,
        'string_line_ending'                               => false,
        // whitespace
        'array_indentation'                                => false,
        'blank_line_before_statement'                      => true,
        'compact_nullable_typehint'                        => true,
        'heredoc_indentation'                              => true,
        'indentation_type'                                 => true,
        'line_ending'                                      => true,
        'method_chaining_indentation'                      => false,
        'no_extra_blank_lines'                             => true,
        'no_spaces_around_offset'                          => true,
        'no_spaces_inside_parenthesis'                     => true,
        'no_trailing_whitespace'                           => true,
        'no_whitespace_in_blank_line'                      => true,
        'single_blank_line_at_eof'                         => true,
    ])
    ->setFinder($finder);
